spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_db
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true